<?php
/**
 * Implements hook_node_info()
 */
function device_node_info() {
    return array(
        'device' => array(
            'name' => t('Device'),
            'base' => 'device',
            'description' => t('You can define new spark-compatible devices here'),
            'has_title' => TRUE,
            'title_label' => t('Product title')
         )
    );
}

/**
 * Implement hook_form()
 */
function device_form($node, $form_state) {
    return node_content_form($node, $form_state);
}