<?php

/**
* Implements hook_block_info().
*/
function doors_menu_block_info() {
  $blocks = array();

  $blocks['YOUR_BLOCK_ABC'] = array(
    'info' => t('YOUR BLOCK NAME'),
  );

  return $blocks;
}

/**
* Implements hook_block_view().
*/
function doors_menu_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'YOUR_BLOCK_ABC':
      if(isset($_GET['clicked_id'])) {
          $node = node_load($_GET['clicked_id']);
          $items = field_get_items('node', $node, 'device_accesstoken');

          $id = field_get_items('node', $node, 'device_deviceid')[0]['value'];
          $at = field_get_items('node', $node, 'device_accesstoken')[0]['value'];
          $delay = field_get_items('node', $node, 'device_delay')[0]['value'];

          $ch = curl_init();
          $url = "https://api.spark.io/v1/devices/". $id ."/toggleLock";

          curl_setopt($ch, CURLOPT_URL, $url);
          curl_setopt($ch, CURLOPT_POST, 1);
          curl_setopt($ch, CURLOPT_POSTFIELDS, "access_token=" . $at . "&arg=" . $delay);
          curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
          $content = curl_exec ($ch);
          curl_close ($ch);
          //echo $content;
      }

      $show_nodes_list = array('device');
      //Based on the node types create a query and then load the node types
      $query = new EntityFieldQuery();
      $query
        ->entityCondition('entity_type', 'node')
        ->entityCondition('bundle', $show_nodes_list)
        ->propertyCondition('status', 1)
        ->addTag('node_access')
        ->propertyOrderBy('created', 'DESC');

      $result = $query->execute();

      $nodes = array();
      if (isset($result['node'])) {
        $nids = array_keys($result['node']);
        $nodes = node_load_multiple($nids);
      }

      $content = "";
      $list = array();
      foreach ($nodes as $node) {
        $options = array('absolute' => TRUE);
        $url = url('node/' . $node->nid, $options);
        $content .= "<div>". $node->title ."<div class='buttons'><a href='?clicked_id=". $node->nid ."'>Open / Close</a></div></div>";
        $list[] = ''.$node->title.'';
      }

      $block = array(
        'subject' => t('My doors'),
        'content' => $content,
      );
      return $block;
  }

  return $block;
}

function _doors_menu_BLOCK_ABC_CONTENT() {
  $output = t('');
  return $output;
}